Dockerfile, README.md
Fixes for #20 #21 
CLA already signed
Build successed: https://registry.hub.docker.com/u/appunite/cloud-sdk/build_id/35948/code/bo4vtfvtpkdbxmyb3juz49/
Cheers :)
=> Fixes for #20 #21 

Dockerfile
The update nag suggests people run an ineffective (because it runs in the short-lived container's filesystem) update command. Let's just turn it off and let people re-pull the image when they want an update.
=> turn off update nags

Dockerfile, test.sh
- update base image
- disable components updater -- any components update changes will be
lost anyway
- disable update check -- updates don't persist anyway
- update the URL with the changed new download location
- change the HOME dir at the start so any subsequent run commands that
change stuff in ~/.config are written to /.config and are actually
visible.
=> Update the gcloud installation dockerfile to play nice in a container

Dockerfile
Added new SDK components:
- Cloud Datastore Emulator
- Cloud Pub/Sub Emulator
These additional components are useful when running Google Cloud Datastore and Pub/Sub in a flexible environment (without Google AppEngine).
=> Added Cloud Datastore Emulator & Cloud Pub/Sub Emulator

Dockerfile, MAINTENENCE.md, README.md, alpine/Dockerfile, centos/Dockerfile, debian_slim/Dockerfile
PR for issue [#74](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/74):
Update baseline image for debian; install all components by default.  Provide -slim and versioned builds.
I'll temp stage the images [here](https://hub.docker.com/r/salrashid123/cloud-sdk-docker/builds/):
- salrashid123/cloud-sdk-docker:latest
- salrashid123/cloud-sdk-docker:latest-slim
- salrashid123/cloud-sdk-docker:159.0.0
- salrashid123/cloud-sdk-docker:159.0.0-slim
- salrashid123/cloud-sdk-docker:legacy-latest
for ref: the dockerhub build rules will look like:
=> Update base image to Debian; all components

Dockerfile, MAINTENENCE.md, README.md, alpine/Dockerfile, debian_slim/Dockerfile
Update sdk Dockerfiles and specify the version inside the docker file.
Major changes:
- This will allow sources retrieved from github tagged Dockerfiles to reflect the version that should actually get installed.   For example, the Dockerfiles in tag [159.0.0](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/releases/tag/159.0.0)  does not specify the version to install; it'll use whatever is there at time of generation (current in apt repo).
Some suggested improvements:
- add dockerhub build rules for alpine version thats also tagged with the sdk release:  eg  :159.0.0-alpine  and :alpine.
cloud sdk now supports version installs so we can make the changes cited above.
```
google-cloud-sdk:
Installed: (none)
Candidate: 159.0.0-0
Version table:
159.0.0-0 0
500 …
```
=> Create versioned and alpine images

Dockerfile, alpine/Dockerfile, debian_slim/Dockerfile
This way it's easier to read the Dockerfiles and patch them simultaneously
with less conflicts.
PTAL @salrashid123
=> Split installed packages onto separate lines

Dockerfile, alpine/Dockerfile, debian_slim/Dockerfile
Adding cbt support;  
added into 162 recently
- [https://cloud.google.com/sdk/downloads#apt-get](https://cloud.google.com/sdk/downloads#apt-get)
google-cloud-sdk-cbt
=> add cbt support; upgrade 162

Dockerfile
The `gcloud docker` subcommand relies on executing a docker client.
This change allows the user to bindmount in the host's docker socket,
and then interact with it using the `gcloud docker` subcommand.
This will only work if the user's host dockerd is compatible with this
docker client, but this is true for all modern versions of docker.
See additional discussion in #97
for why bindmounting in the client's docker binary is non-ideal.
The `docker` image was used to source the docker client binary as a
matter of convenience.
The change is intentionally only applied to the  'debian'
variant of the image, not the 'alpine' nor  '-slim' ones. This is to keep the 'slim'
image slim.
Fixes #97
=> Add docker client to 'thick' image

Dockerfile, alpine/Dockerfile, debian_slim/Dockerfile
This adds a "the binary runs" check to the end of each container's list
of commands.
The primary benefit this has is that a build will fail if any of those
commands don't work, which is preferable to a bad release being made.
As a small secondary benefit, it also includes the `version` output in
the build log.
Ideally, a more complete functional test would be done on each image
prior to push, but since dockerhub automated builds are being used,
there's no great place to insert those tests.
I think this is enough of an improvement to be worth doing.
This was split out from #101 where I originally included it, but was requested to add them separately.
=> Add an 'it runs' failsafes to binaries

Dockerfile
This updates the docker client included for the `gcloud docker`
subcommand to the current stable version.
=> Update docker client to 17.12

Dockerfile, debian_slim/Dockerfile
Fixes https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/94
Instlals `gcloud` under `/opt/google-cloud-sdk/` and adds to the path
Updated `Dockerfile` has
```
Your current Cloud SDK version is: 239.0.0
The latest available version is: 239.0.0
+---------------------------------------------------------------------------------------------------------+
|                                                Components                                               |
+-----------+------------------------------------------------------+--------------------------+-----------+
|   Status  |                         Name                         |            ID            |    Size   |
+-----------+------------------------------------------------------+--------------------------+-----------+
| …
```
=> Use .tar.gz installer for cloud sdk

alpine/Dockerfile, debian_slim/Dockerfile
This change adds Docker to the Slim and Alpine image variants using the same model in the main Dockerfile.
The main container image is in the ~700MB zone.
For a baseline CI/CD use case, many of the extra packages there may not be needed, but it's very likely that docker will be. I have seen a number of alpine glcoud + docker images in the wild. In practice, the size difference can save minutes off a pipeline with multiple jobs on a service such as GitLab CI or CircleCI.
=> Add docker client to slim and alpine

Dockerfile
```
docker run --rm --volumes-from my-project google/cloud-sdk gcloud container clusters get-credentials my-cluster --project my-project #set up .kube
docker run --rm --volumes-from my-project google/cloud-sdk kubectl get pod
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
I think it would be more appropriate that kubectl config should be persisted when we use `docker run --volume-from`.
=> add VOLUME .kube

README.md
In some secured Linux, allocate a tty is disabled. e.g. in Jenkins CI/CD process
Issue reference: https://stackoverflow.com/questions/43099116/error-the-input-device-is-not-a-tty
Remove unnecessary `docker run -ti` will solve this issue also make a good understanding of docker run.
=> remove unnecessary docker run -ti

Dockerfile, Dockerfile.workingWith3Removed, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
Added credential helper for git access to Cloud Source Repositories using application default credentials.
https://github.com/GoogleCloudPlatform/cloud-builders/issues/676
=> Added git credential helper for CSR

README.md
`gcloud auth login` is not enough to authenticate the applications using Google Cloud APIs (e.g., the `Client` of `google-cloud-bigquery`): to update the Application Default Credentials the `--update-adc` option is required.
This PR adds this explanation to the README.md.
=> README: explain how to authenticate API clients

Dockerfile, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
As per GCP's [best practices](https://cloud.google.com/solutions/best-practices-for-operating-containers#avoid_running_as_root), it is recommended not to run containers as the `root` user.
Fixes #154 
Fixes #199
=> Allow image to be run as non-root user

README.md
This is best practice, in general, but listing it here makes clear statement
that we can modify behaviour between versions without a warning.
=> Add note to always pin version of docker images.

alpine/Dockerfile
Updated alpine version from 3.11 to 3.12 to counter some CVE's that occur when installing some additional tooling like `jq` when using this image as a basis for your own.
=> Updated alpine version from 3.11 to 3.12 to counter CVE's

README.md
This is a bit of a hidden option of the Google Cloud SDK, although some explicit use cases are mentioned in the documentation.
I think this is especially useful in CI.
=> Document CLOUDSDK_ environment variables

emulators/Dockerfile
```sh
$ dockle gcr.io/google.com/cloudsdktool/google-cloud-cli:386.0.0-emulators
...
FATAL	- DKL-DI-0005: Clear apt-get caches
* Use 'rm -rf /var/lib/apt/lists' after 'apt-get install|update' : RUN |1 CLOUD_SDK_VERSION=386.0.0 /bin/sh -c ARCH=`cat /tmp/arch` &&     mkdir -p /usr/share/man/man1/ &&     apt-get update &&     apt-get -y install         curl         python3         python3-crcmod         bash         openjdk-11-jre-headless &&     curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz &&     tar xzf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz &&     rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz &&     gcloud config set core/disable_usage_reporting true &&     gcloud config …
```
=> emulators: add a step to rm cache and tmp files

Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile, emulators/Dockerfile
Per https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/272#issuecomment-1091877037, Debian Buster is EOL in August 2022. 
This PR updates base images to `debian:bullseye` and closes #272
=> Update images to use Debian Bullseye as base

README.md
Cloud Build Local Builder is obsolete. While it is still included for installation via Cloud SDK, it is hidden and its use is no longer supported.
=> Remove Local Builder details.

README.md
Small component list update of the Readme file.
Checked x86_64 docker images, only.
Some components are not available on ARM right now. Should some packages marked as 'x86_64 only' or something like that?
=> Update README components list

debian_component_based/Dockerfile
fixes: #290
this pr would add `openjdk-11-jre-headless` as it's currently used in the [emulators/Dockerfile](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/b1077cac9dd65fb372a1e5c8ecfc10c38592953c/emulators/Dockerfile#L24)
**_before_** this pr, there was an error described in the issue #290 that prevented the pub/sub emulator from starting
**_after_** this pr, the logs show the correct startup:
```
DEBUG: Running [gcloud.beta.emulators.pubsub.start] with arguments: [--host-port: "<googlecloudsdk.calliope.arg_parsers.HostPort object at 0xffff96221850>", --log-http: "true", --project: "localrun", --user-output-enabled: "true", --verbosity: "debug"]
DEBUG: Found Cloud SDK root: /google-cloud-sdk
Executing: /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator …
```
=> add missing jre to debian_component_based image

Dockerfile, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
The latest docker releases contain several security fixes.
I suggest to update the old docker binary to fix more than 23 vulnerabilities (result by Google Cloud Container Analysis scanning API) in Google Cloud CLI Docker image.
For more details check the CVEs on the release page
https://github.com/moby/moby/releases
=> Update static docker source to v20.10.21

Dockerfile
Cause of #230 the pyopenssl python package was added to the `:latest` Dockerfile as a dependency of `gsutil signurl`.
Tried the `:slim` Docker image (already/still) without pyopenssl and the `gsutil signurl` command is running without an issue.
Removing pyopenssl in `:latest` does not break the `gsutil signurl` command.
```
gsutil signurl -r <region> <private-key-file> gs://<bucket>/<object> 
```
Is it safe to remove the 'unused' python package in the latest Debian based Docker image? Or are there different dependency to the pyopenssl package?
The `:alpine` image still requires the `py3-openssl` to run `gsutil signurl` somehow.
=> Remove pyopenssl python package

Dockerfile, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
The latest v20.10.x docker bugfix release.
https://github.com/moby/moby/releases/tag/v20.10.23
=> Update static docker source to v20.10.23

Dockerfile, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
The latest docker release contains several security fixes.
https://github.com/moby/moby/releases/tag/v20.10.24
=> Update static docker source to v20.10.24

Dockerfile, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
The latest docker release contains several security fixes (in Packaging Updates).
https://github.com/moby/moby/releases/tag/v20.10.25
=> Update static docker source to v20.10.25

Dockerfile, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
There is a mistake in my pull request #326 the Docker image `docker:20.10.25` will not be available. It seems they stopped building and providing binary builds of the v20.10 branch https://github.com/docker-library/docker/pull/426
This pull request updates the Docker version to the latest release of v23.0
https://github.com/moby/moby/releases/tag/v23.0.6
https://github.com/moby/moby/releases/tag/v23.0.5
https://github.com/moby/moby/releases/tag/v23.0.4
https://github.com/moby/moby/releases/tag/v23.0.3
https://github.com/moby/moby/releases/tag/v23.0.2
https://github.com/moby/moby/releases/tag/v23.0.1
https://github.com/moby/moby/releases/tag/v23.0.0
I am not sure if the new Docker releases are compatible at all.
=> Update static docker source to v23.0.6

Dockerfile, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
The latest docker release contains several security fixes (see Packaging Updates).
https://github.com/moby/moby/releases/tag/v24.0.3
=> Update static docker source to v24.0.4

Dockerfile, alpine/Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
The latest docker release contains several security fixes (see Packaging Updates).
https://github.com/moby/moby/releases/tag/v24.0.5
https://github.com/moby/moby/releases/tag/v24.0.6
=> Update static docker source to v24.0.6

README.md
=> Add gcompat package to Alpine example (required by kubectl)

Dockerfile, debian_component_based/Dockerfile, debian_slim/Dockerfile
Compared the Debian based Dockerfiles and unified the files somehow
1)  The path `/opt/google-cloud-sdk/` does not exist, remove `PATH` extension
2) `apt-key` is deprecated in Debian 11, switch to recommended way by docs https://cloud.google.com/sdk/docs/install-sdk#deb
3) Switch to `python3-crcmod` deb package in `:slim` image (already in `:latest` by 2e81e4a496b9aa8940157ce52212b5371864a82e)
4) minor changes
=> Unify Debian based Dockerfiles

alpine/Dockerfile
At the moment the `alpine:3.18` Docker image is not up 2 date. Missing some security updates e.g. for Openssl packages.
```
$ docker pull alpine:3.18 
3.18: Pulling from library/alpine
Digest: sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978
Status: Image is up to date for alpine:3.18
docker.io/library/alpine:3.18
$ docker run --rm -it alpine:3.18 
/ # apk --no-cache upgrade
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/7) Upgrading musl (1.2.4-r1 -> 1.2.4-r2)
(2/7) Upgrading busybox (1.36.1-r2 -> 1.36.1-r5)
Executing busybox-1.36.1-r5.post-upgrade
(3/7) Upgrading busybox-binsh (1.36.1-r2 -> 1.36.1-r5)
(4/7) Upgrading libcrypto3 (3.1.3-r0 -> …
```
=> Add apk upgrade to Alpine based Docker image

debian_slim/Dockerfile
fix apt-key deprecated
doc: [https://wiki.debian.org/SecureApt](https://wiki.debian.org/SecureApt)
=> fix apt-key deprecated

cloudbuild.yaml, generate_cloudbuild.py, stable/Dockerfile
=> add new stable-alpha image

README.md, cloudbuild.yaml, generate_cloudbuild.py, stable/Dockerfile
Release new `:stable` docker image for gcloud cli. This is going to be the default docker image going forward.
=> Release stable image as default image for gcloud

alpine/Dockerfile
Rolling back alpine image to version 3.19 due to the issue: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/497
We'll upgrade the alpine image to version 3.20 after the holidays once we had verified the gsutil compatibility with python 3.12.
=> rollback alpine image to version 3.19

stable/Dockerfile
This step sometimes results in a build failure e.g.:
find: '/proc/44': No such file or directory
This can happen if the find results include /proc/<PID> files for processes that have finished between the time when `find` reads the name of the file in the directory and when it goes to stat the file (see -ignore_readdir_race in `man find`).
In our case, all the pycache dirs and .pyc files come from the /usr/lib/google-cloud-sdk directory, so we can just restrict the search to there instead of the root directory.
=> Fix `find` including nonexistent files when cleaning up .pyc files.

alpine/Dockerfile, debian_component_based/Dockerfile
This change should not be submitted before the next gcloud release 518.0.0 (scheduled on April 15, 2025). The documentation update ([devsite](https://cloud.google.com/sdk/docs/downloads-docker#whats_new_important_updates)) is completed and we should release the new gcloud images (`:alpha` abd `:debian_component_based`) in the next release v519.0.0.  
bug: [b/394287492](https://b.corp.google.com/issues/394287492)
=> Remove docker-buildx from alpine and debian_component_based image

Dockerfile, debian_slim/Dockerfile
We are removing the `docker-buildx` dependency from all Google Cloud CLI Docker images to mitigate customers’ exposure to vulnerabilities found in this component and its dependencies according to the following timeline. If your workflows rely on `docker-buildx`, you will need to pin to the respective `Pin-To` gcloud version or earlier. Alternatively, you could build your own docker image and include `docker-buildx` using a custom Dockerfile. Here are some examples: [Dockerfile Examples](https://cloud.google.com/sdk/docs/dockerfile_example). For any questions or concerns about the change, reach out to the [gcloud support team](https://b.corp.google.com/issues/new?component=187143&pli=1&template=800102).
|  Date  | Removed in gcloud version | `Pin-to` gcloud version to continue using …
=> Update `:latest` and `:slim` Dockerfile

all_components/Dockerfile
Modified to install components that are unavailable on ARM only when running on x86_64.
```
ERROR: (gcloud.components.install) The following components are unknown [cloud-spanner-emulator, spanner-migration-tool].
```
=> Install ARM-unavailable components only on x86_64

README.md
Adding `make` to the list of packages that will be removed from gcloud CLI docker images
=> Update warning to add communication about removing `make` package

Dockerfile, all_components/Dockerfile, debian_component_based/Dockerfile, emulators/Dockerfile
Datastore and Firestore team are releasing a new version of emulators on July 01, 2025, which will require java 21. As a result if we don't upgrade the java version for gcloud docker images customer workflow will break: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/discussions/564
This PR updates the java version for gcloud docker images to reduce customer friction.
=> Upgrade to java 21 for datastore and firestore emulators support 

Dockerfile, debian_component_based/Dockerfile
We are removing the `make` dependency from the `:latest` and `:debian_component_based` Google Cloud CLI Docker images to mitigate customers' exposure to vulnerabilities found in this component and its dependencies according to the [following timeline](#update-timeline). If your workflows rely on the `make` package, you will need to pin to the respective `Pin-To` gcloud version or earlier. Alternatively, you could build your own docker image and include `make` using a custom Dockerfile. 
|  <img width=100/> Date  | Removed in gcloud version | `Pin-to` gcloud version to continue using `make` | `make` removed from images | 
|:----------:|:-------------------------------------------:|:--------------------:|:----------:| 
| Aug 5, 2025 | 533.0.0 | 532.0.0 | `:latest` and …
=> Update Dockerfile for `:latest` and `:debian_component_based` images to remove `make` package

Dockerfile, cloudbuild-hotfix.yaml, cloudbuild.yaml, generate_cloudbuild.py
Add Arm support for the latest docker image.
Important note: `cloud-spanner-emulator` component is not supported on ARM.
=> Add Arm support for the latest docker image
