- README.md
> README: add reference to preview components

- Dockerfile
Added components 
- cloud-datastore-emulator
- app-engine-go
This closes #42
> Add cloud-datastore-emulator and app-engine-go components

- Dockerfile
closes https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/46
adds bigtable component
> add bigtable to list of additional components

- README.md
Update doc on git and dockerhub regarding source image rebase
> Add rebase notice

- README.md
I think this one is a typo.
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
> fix bad command in readme

- README.md
Sorry about that.
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
> Fix typo which was previously a typo too

- Dockerfile
- hooks/pre-commit
This should allow for existing dockerhub triggers to generate too.
> Move primary Dockerfile to root

- README.md
@salrashid123 PTAL
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
> Add fancy Docker Hub badges

- Dockerfile
- alpine/Dockerfile
- debian_slim/Dockerfile
openssh for gcloud compute, git for cloud source
> Add git, sshclient

- Dockerfile
- alpine/Dockerfile
- debian_slim/Dockerfile
Update SDK version to `171.0.0 `.
> Update SDK to 171.0.0

- Dockerfile
- alpine/Dockerfile
- debian_slim/Dockerfile
177.0.0 has been released 2017-10-25.
> Update Cloud SDK version to 177.0.0

- Dockerfile
- alpine/Dockerfile
- debian_component_based/Dockerfile
- debian_slim/Dockerfile
Fixes https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/187
> Update to Python3

- alpine/Dockerfile
- debian_component_based/Dockerfile
- debian_slim/Dockerfile
Minor tidy up for maintainability!
> Tidy up envs and args in order for Dockerfile

- Dockerfile
- alpine/Dockerfile
- debian_component_based/Dockerfile
- debian_slim/Dockerfile
Reverts GoogleCloudPlatform/cloud-sdk-docker#213
Several users are seeing permission errors.
> Revert "Allow image to be run as non-root user"

- Dockerfile
> Added spanner and firestore emulators

- alpine/Dockerfile
Includes fixes for multiple python related CVEs.
> Update to the latest alpine image 3.13

- cloudbuild.yaml
Add [eu, asia, us] prefixes to gcr.io images as requested by https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/239
> update name for steps to be image

- Dockerfile
- alpine/Dockerfile
- debian_component_based/Dockerfile
- debian_slim/Dockerfile
- emulators/Dockerfile
Reimplements #213 but without changing the default `USER` and `VOLUME`, allowing to add this feature without being a breaking change.
> add non-root user

- Dockerfile
#279 - https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
> Install google-cloud-sdk-gke-gcloud-auth-plugin

- README.md
Datalab was remove by a293a0862fd226d2ca78208d16057be9c1d02ec6 and b9e9949bfab1269b6570467e4bb5000fa1810159
> Update README components list 414.0.0

- Dockerfile
- alpine/Dockerfile
- debian_component_based/Dockerfile
- debian_slim/Dockerfile
Might fix https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/331
> Update static docker source to v24.0.1 and add buildx

- alpine/Dockerfile
Fix https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/336
> Update alpine linux version to 3.18

- README.md
Update some docker examples and references to the docs
> README: update docker examples and docs references

- Dockerfile
- alpine/Dockerfile
- debian_component_based/Dockerfile
- debian_slim/Dockerfile
The latest docker release contains several security fixes
https://github.com/moby/moby/releases/tag/v24.0.7
> Update static docker source to v24.0.7

- cloudbuild-hotfix.yaml
- generate_cloudbuild.py
generate cloudbuild config for a hotfix releaseof docker images
> generate cloudbuild config for a hotfix releaseof docker images

- alpine/Dockerfile
Reverts GoogleCloudPlatform/cloud-sdk-docker#569
> Revert "Bump alpine from 3.20 to 3.22 in /alpine"

- Dockerfile
- all_components/Dockerfile
- debian_component_based/Dockerfile
- emulators/Dockerfile
Reverts GoogleCloudPlatform/cloud-sdk-docker#582
> Revert "Upgrade to java 21 for datastore and firestore emulators support "
